"""Artifact value object: a file generated by an agent for a task."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

__all__ = ["Artifact"]


@dataclass
class Artifact:
    """Describe an artifact generated by the agent for a task."""

    path: Path
    name: str
    mime_type: str
    safe_to_share: bool = False
