import mimetypes
import logging

from khl import Message, MessageTypes

from src import __version__ as version
from src.application.handle_result import HandleResult
from src.core.contracts.agent import AgentResult
from src.i18n import Language, MessageKey, kook_message

log = logging.getLogger(__name__)


class KookRenderer:
    """Render message-handling outcomes as KOOK messages and shared artifacts.

    All KOOK user-facing copy is produced here (the presenter for the KOOK
    adapter), so the application layer and the agent stay platform-agnostic.
    """

    def __init__(self, asset_client=None, language: Language = "CN") -> None:
        """Initialize the KOOK result renderer.

        Args:
            asset_client: Optional KOOK client used to upload generated artifacts.
            language: Language used for messages returned to KOOK users.
        """
        self._asset_client = asset_client
        self._language = language

    async def render(self, source: Message, outcome: HandleResult) -> None:
        """Render a :class:`HandleResult` as a reply to ``source``.

        Args:
            source: The KOOK message to reply to.
            outcome: The outcome produced by the application use case.
        """
        if outcome.status == "duplicate":
            # Already processed — never send a duplicate reply.
            return

        if outcome.status == "rejected":
            await self._render_rejection(source, outcome)
            return

        if outcome.status == "failed":
            await self._reply(source, kook_message(self._language, "processing_failed"))
            return

        result = outcome.result
        if result is None:
            await self._reply(source, kook_message(self._language, "empty_result"))
            return

        if result.status == "failed":
            await self._reply(source, kook_message(self._language, "processing_failed"))
            return

        if result.status == "waiting_user":
            await self._reply(
                source, kook_message(self._language, "file_instructions_required")
            )
            return

        # Completed result: text first, then shareable artifacts.
        await self._reply(
            source,
            result.text or kook_message(self._language, "empty_result"),
        )
        await self._render_artifacts(source, result)

    async def _render_rejection(self, source: Message, outcome: HandleResult) -> None:
        """Render a rejected outcome (e.g. too many attachments)."""
        reason = outcome.reason or "rejected"
        key: MessageKey = (
            "too_many_attachments" if reason == "too_many_attachments" else "processing_failed"
        )
        if key == "too_many_attachments":
            await self._reply(
                source,
                kook_message(self._language, key, version=version),
            )
        else:
            await self._reply(source, kook_message(self._language, key))

    async def _render_artifacts(self, source: Message, result: AgentResult) -> None:
        """Upload and send shareable artifacts generated by the agent."""
        for artifact in result.artifacts:
            if not artifact.safe_to_share:
                continue
            if self._asset_client is None:
                raise RuntimeError("The renderer has no configured asset client.")
            try:
                url = await self._asset_client.create_asset(artifact.path)
                guessed = (
                    artifact.mime_type
                    or mimetypes.guess_type(artifact.name)[0]
                    or ""
                )
                message_type = (
                    MessageTypes.IMG if guessed.startswith("image/") else MessageTypes.FILE
                )
                await source.reply(url, type=message_type, use_quote=False)
            except Exception:
                log.exception("failed to upload artifact %s", artifact.name)
                await source.reply(
                    kook_message(
                        self._language,
                        "artifact_upload_failed",
                        name=artifact.name,
                    ),
                    type=MessageTypes.KMD,
                    use_quote=False,
                )

    async def _reply(self, source: Message, text: str) -> None:
        """Send a plain Markdown reply to ``source``."""
        await source.reply(text, type=MessageTypes.KMD)
